sudo: required
language: php
php:
- 5.5
- 5.6
install:
- composer self-update
before_script:
- composer install --prefer-source --no-interaction --dev
- composer dump-autoload --optimize
script: phpunit
matrix:
  allow_failures:
  - php: 5.4
  - php: hhvm
  fast_finish: true
notifications:
  on_success: always
  on_failure: always
env:
  global:
  - secure: 090F0/reMxRnHG3v1XPcKzY7W6zuaUAttIorcKEa2snSkwpjHUNwcc/FRwdX1lSMrr9xpC4Oy2BKfpIYTv1wvn5LgRs5gwpIdtC4cCNIT8mwPxAnabbrEJ0t7AL2SS/G03K+NdpeGJ0i1luvkPMb5F+HoPMfgNYW8t4S5FAtbM6QDP30yT4iJUZ7FA15dGOOJIEE/uA3z96vA0CMfzQR7zptqYYuYkqSNS+y/EIGFRq5zd0IbM0yKIlLDM3Io672uFnO5iwDHthODt6dy413oHd1RtLmU1gzlgW4BGjajNaOhEG6rGXqu64tBbvX5kMhmTm23a02EmHYe9Q67jGrI0dfOLnGtS2S0JRrHebgPDNsHprA40vEb9NVED1rU3TfJGfmR1wN8aMp0Pepxvs2SCFyKT78+OP8nRM3NIJjyUGIlA842d7pOZJ+ngXIGCJJl1CV5zwx1m6JJRImiU1t/iZkeQ3T3iSmG3JVhHszEfliL37pmybjp3yWISea6Mpi3V39QwYNWPBMlX6U5Nr3tKjnWlV6D11AVcXUCN/Rgriwqd+alkM1Cvv4ik3g23Tvdjd9c1uLf5HYTUTnztqpVtDZo2Sw2fDHnh7UWozSquPgIl9GBwNXD6X4sDOoncFrF4HmIFV1Gr7RUWNVPf7BAnNNCpEKeyeRtpR6PfEjM80=
  - secure: QG6IhsnF+1PWmfcjBma+qfIm3bjpDn7t+0V03JkYyz1PYR67PdEzzfkBsue/RIad2cPiJH3v139SnO1XrQBwFil7WFEchizWZxNNqvpsoi8WthCeHi37QNj0BnUUq9XI047dQMhQ+1nkvLw9EJZ6fPK2u+xIL1H/V4Ep/aQY2hVnpFSvSXoRTdnPptzQSwBOIAvSR3R+KsDTOBJgNn7R4xbyuahY0UUlmVNzYCC3hYdjzO9Dz+MJoM6+Mosjx/Hw7IeU/9vnUWGFqxikWi9Uwoi4Crib7nSJcUUviXgFJqa6OxeIOD2VDwuLRcEO6aIkXydUDGr0yTR23ulG+YNemuQrChTCesH8IISxNMo6P7Sy3cZan2FPj07a2rdh7OKmRXF7VrxSd+zogcy/4ZDDa0vxEZZ+hzYpvD6L7LsPzxeuiJ/qVR2fjCnX5N9sIqppjNZ21F73Ffkrrb5g7p/jX7S0Zxxg0Ja2ZOn3/GgLQpdhO0nf9Whz8ZVR4eDf+f/Qvi4ryoDStzugKNX00UpYsNDg6yRjCr9t1hxJgpIeSFVX0vK3ddqNnvZhh6RlJNCdIaxkFvkmzfycIkAkWSpH6TcLpsWCU26PGqm+mHfcSNXcpbTagrYqah0wXZMHKRY9s6bRfko3XAPaCX6JmZ1j3QqLRXx3RmR24QCN78ZMoyQ=
after_success:
- bash .scripts/deploy_buddy.sh
before_install:
- mkdir .keys
- touch .keys/deploy_key.pem
- openssl aes-256-cbc -nopad -K $encrypted_fd30640532d7_key -iv $encrypted_fd30640532d7_iv -in deploy_key.pem.enc -out .keys/deploy_key.pem -d
